totrt: False

# yolo 權重路徑
model:
  weight: '/home/insign/Doc/insign/flexible-yolov5/Polyp/AI_box_0706_toTRT/weights/best.pt'

# maskrcnn 權重路徑
maskrcnn:
  weight: 'run/0921/best.pt'

nms:
  conf_thres: 0.5
  iou_thres: 0.5
  classes: 0
  agnostic_nms: False

data:
  root: "Polyp"
  img_dir: "Images"
  mask_dir: "Masks"

optimizer: "Adam"

num_epochs: 200


